[package]
name = "stock-sim"
version = "0.1.0"
authors = ["Connor Wenck <none@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8"
rand = "0.8"
rayon = "1.5"
once_cell = "1.7"
csv = "1.1"